module.exports =
  PLAYER           : '@'
  PLAYER_PAUSED    : '?'
  FROG             : '*'
  GECKO            : 'G'
  BULLFROG         : 'B'
  TOAD             : 'T'
  AXOLOTL          : 'A'
  GROUND           : '.'
  NO_MANS_LAND     : '#'
  WALL_HORIZONTAL  : '-'
  WALL_VERTICAL    : '|'
  WALL_END         : '+'
  WALL_TOPLEFT     : '{'
  WALL_TOPRIGHT    : '}'
  WALL_BOTTOMLEFT  : '['
  WALL_BOTTOMRIGHT : ']'
